name: Feature
description: New capability or enhancement
title: "[FEAT] "
labels: ["prophet-kind-feature","prophet-status-triage"]
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: ["prophet-priority-p0","prophet-priority-p1","prophet-priority-p2","prophet-priority-p3"]
    validations: { required: true }
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What outcome do we want?
    validations: { required: true }
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Testable bullets.
    validations: { required: true }
  - type: textarea
    id: evidence
    attributes:
      label: Evidence plan
      description: Links we will produce (tests, PRs, runbooks, screenshots).
    validations: { required: true }
